apiVersion: machinelearning.seldon.io/v1
kind: SeldonDeployment
metadata:
  name: churn-custom
  namespace: ml-production
spec:
  name: churn-custom

  predictors:
  - name: default
    replicas: 1

    graph:
      name: churn-model
      type: MODEL
      endpoint:
        type: REST

    componentSpecs:
    - spec:
        containers:
        - name: churn-model
          image: 112277641321.dkr.ecr.us-east-1.amazonaws.com/churn-model:v1
          imagePullPolicy: Always